### ISSUE TITLE
incompatible statements

### ISSUE THREAD

**Issue by hhelibeb** [abaplint/stats.abaplint.org#10]
Sometimes, the Statement Compatibility function shows there are some incompatible statements on any ABAP version.

For example, 
https://stats.abaplint.org/#/-/hhelibeb/abap-data-validator (12 incompatible statements)
https://github.com/abapinho/abapBlame/tree/master/src (6 incompatible statements)
The abap-data-validator is a quite simple project which has only 12 classes + 1 interface. And it is unit tested in my 7.40/7.50 environment.
![图片](https://user-images.githubusercontent.com/16676760/71762843-cb4c1f80-2f0f-11ea-8da9-6271c72a02f4.png)

How can I find the statements which didn't pass the test?  I read the code about stats.abaplint.org
 and only found the incompatible = data.totals.statements - object.count but still didn't find the concrete incompatible statements.

Thanks.

**Comment by larshp** [comment]
scroll down to "parser_error"s, for abap-data-validtor it is the below. There are some twists in abaplint, so it does not show exactly the correct result, plus it has bugs 😄 

![image](https://user-images.githubusercontent.com/5888506/71763137-60332680-2ed8-11ea-9a56-12dd867e4051.png)

**Comment by larshp** [comment]
and if there is no `abaplint.json` file in the repo it just runs with the default configuration, which contains a lot of stuff that might not be considered as errors

**Comment by hhelibeb** [comment]
Thank you larshp. I will try to change my code and set up a abaplint.json.

**Comment by larshp** [comment]
you can also try setting up https://github.com/apps/abaplint, then it will automatically run for each push or pull request

**Comment by hhelibeb** [comment]
> 
> 
> you can also try setting up https://github.com/apps/abaplint, then it will automatically run for each push or pull request

wow! it' amazing... I will introduce it to my friends.

**Comment by larshp** [comment]
see example runs on https://app.abaplint.org/, it also helps keeping an eye on what is happening, and finding false positives

**Comment by hhelibeb** [comment]
I collected some information and wrote a chinese [blog post](https://www.cnblogs.com/hhelibeb/p/12166288.html) to introduce abaplint. Hope more and more developers join the community to share their ideas and works with abapgit/abaplint.

**Comment by larshp** [comment]
cool, thanks, are you on twitter?

**Comment by hhelibeb** [comment]
no, for some unknown reason, twitter blocks users with mainland China phone number. I will follow you when twitter is avaliable to me.😅
